/**
 * MobTrack Over-The-Air Update Publisher
 *
 * Designed for Android Studio builds with collaborator isolation.
 * Automatically detects the latest APK generated by Android Studio,
 * reads developer target number (to avoid affecting teammates),
 * uploads to Supabase Storage, and publishes the version feed.
 *
 * Usage:
 *   npm run publish-update
 *   npm run publish-update -- --version 1.0.1 --code 2 --target 6363738923 --notes "Bug fixes"
 */

const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

// Supabase project credentials (same as configured in supabase.ts)
const SUPABASE_URL = 'https://bmqmdykqrnocjyqjjtzb.supabase.co';
const SUPABASE_KEY = 'sb_publishable_43VlpJVrEI8fzut89x0Isg_kq6G32CU';
const BUCKET_NAME = 'secure_media';

// Parse command-line flags
const args = process.argv.slice(2);
function getArg(flag, defaultValue) {
  const index = args.indexOf(flag);
  if (index !== -1 && index + 1 < args.length) {
    return args[index + 1];
  }
  return defaultValue;
}

// Find all APKs recursively
function findApks(dir) {
  let results = [];
  if (!fs.existsSync(dir)) return results;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(findApks(full));
    } else if (entry.isFile() && entry.name.endsWith('.apk')) {
      results.push(full);
    }
  }
  return results;
}

async function main() {
  console.log('📦 Preparing MobTrack OTA Update...');

  const rootDir = path.resolve(__dirname, '..');
  const apkDir = path.join(rootDir, 'android', 'app', 'build', 'outputs', 'apk');

  // Determine target phone number for team isolation
  let targetNumber = getArg('--target', null);
  const devConfigPath = path.join(rootDir, 'mobtrack.dev.json');
  if (!targetNumber && fs.existsSync(devConfigPath)) {
    try {
      const devConfig = JSON.parse(fs.readFileSync(devConfigPath, 'utf8'));
      targetNumber = devConfig.targetNumber || null;
    } catch (_) {}
  }
  if (!targetNumber) {
    console.error('\n❌ Error: No target phone number specified!');
    console.error('👉 Pass --target <phone_number> or configure targetNumber in mobtrack.dev.json');
    console.error('   This prevents accidentally overwriting another teammate\'s channel.\n');
    process.exit(1);
  }

  const updatesFolder = `app_updates/${targetNumber}`;

  let targetApkPath = getArg('--apk', null);

  if (!targetApkPath) {
    const allApks = findApks(apkDir);
    if (allApks.length > 0) {
      // Pick the newest APK built by Android Studio
      allApks.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
      targetApkPath = allApks[0];
    }
  }

  if (!targetApkPath || !fs.existsSync(targetApkPath)) {
    console.error(`\n❌ Error: No APK found in:\n   ${apkDir}`);
    console.error('👉 In Android Studio: Click "Build > Build Bundle(s) / APK(s) > Build APK(s)"\n');
    process.exit(1);
  }

  // Auto-detect versionCode and versionName from android/app/build.gradle
  const buildGradlePath = path.join(rootDir, 'android', 'app', 'build.gradle');
  let gradleVersionName = '1.0.0';
  let gradleVersionCode = 1;
  if (fs.existsSync(buildGradlePath)) {
    const gradleContent = fs.readFileSync(buildGradlePath, 'utf8');
    const codeMatch = gradleContent.match(/versionCode\s+(\d+)/);
    const nameMatch = gradleContent.match(/versionName\s+["']([^"']+)["']/);
    if (codeMatch) gradleVersionCode = parseInt(codeMatch[1], 10);
    if (nameMatch) gradleVersionName = nameMatch[1];
  }

  const versionName = getArg('--version', gradleVersionName);
  const versionCode = parseInt(getArg('--code', String(gradleVersionCode)), 10);
  const notes = getArg('--notes', 'New update with performance improvements and bug fixes.');

  // Device-level isolation: only a specific physical device can see the update
  let targetDeviceId = getArg('--device-id', null);
  if (!targetDeviceId && fs.existsSync(devConfigPath)) {
    try {
      const devConfig = JSON.parse(fs.readFileSync(devConfigPath, 'utf8'));
      targetDeviceId = devConfig.targetDeviceId || null;
    } catch (_) {}
  }

  const stats = fs.statSync(targetApkPath);
  const sizeMB = (stats.size / (1024 * 1024)).toFixed(2);
  const relPath = path.relative(rootDir, targetApkPath);

  console.log(`\n👤 Target Channel / Phone : ${targetNumber} (Team-Isolated)`);
  if (targetDeviceId) {
    console.log(`📱 Target Device ID      : ${targetDeviceId} (Only this physical device)`);
  }
  console.log(`📁 Detected APK from Android Studio : ${relPath} (${sizeMB} MB)`);
  console.log(`🕒 Built at : ${new Date(stats.mtime).toLocaleString()}`);
  console.log(`📄 App Version : ${versionName} (Build Code: ${versionCode})`);
  console.log(`📝 Release Notes : ${notes}`);

  const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

  // Check existing files to avoid collision in this user's folder
  const { data: existingList } = await supabase.storage
    .from(BUCKET_NAME)
    .list(updatesFolder);

  const existingNames = new Set((existingList || []).map(f => f.name));

  let apkFileName = `MobTrack-v${versionName}-b${versionCode}.apk`;
  if (existingNames.has(apkFileName)) {
    apkFileName = `MobTrack-v${versionName}-b${versionCode}-${Date.now()}.apk`;
  }
  const apkStoragePath = `${updatesFolder}/${apkFileName}`;

  console.log(`\n⬆️  Uploading APK to Supabase Storage (${apkStoragePath})...`);
  const apkBuffer = fs.readFileSync(targetApkPath);

  const { error: uploadError } = await supabase.storage
    .from(BUCKET_NAME)
    .upload(apkStoragePath, apkBuffer, {
      contentType: 'application/vnd.android.package-archive',
    });

  if (uploadError) {
    console.error('\n❌ Failed to upload APK to Supabase Storage:', uploadError.message);
    process.exit(1);
  }

  const { data: publicUrlData } = supabase.storage
    .from(BUCKET_NAME)
    .getPublicUrl(apkStoragePath);

  const apkUrl = publicUrlData.publicUrl;

  console.log('✅ APK uploaded successfully!');
  console.log(`🔗 APK URL: ${apkUrl}`);

  // Publish version metadata feed
  const versionMeta = {
    versionCode,
    versionName,
    apkUrl,
    fileSize: stats.size,
    fileSizeMB: `${sizeMB} MB`,
    notes,
    targetNumber,
    ...(targetDeviceId ? { targetDeviceId } : {}),
    releasedAt: new Date().toISOString(),
  };

  let metaFileName = `v_${versionCode}_${versionName}.json`;
  if (existingNames.has(metaFileName)) {
    metaFileName = `v_${versionCode}_${versionName}_${Date.now()}.json`;
  }
  const metaStoragePath = `${updatesFolder}/${metaFileName}`;

  console.log(`\n⬆️  Publishing metadata feed (${metaStoragePath})...`);
  const metaBuffer = Buffer.from(JSON.stringify(versionMeta, null, 2), 'utf8');

  const { error: metaError } = await supabase.storage
    .from(BUCKET_NAME)
    .upload(metaStoragePath, metaBuffer, {
      contentType: 'application/json',
    });

  if (metaError) {
    console.error('\n❌ Failed to upload version metadata:', metaError.message);
    process.exit(1);
  }

  console.log('✅ Version metadata published!');

  console.log('\n===========================================================');
  console.log('🎉 MOBTRACK OTA UPDATE IS LIVE (TEAM-ISOLATED)!');
  console.log('===========================================================');
  console.log(`Target Phone  : ${targetNumber} (Only this phone receives this update)`);
  console.log(`Version       : ${versionName} (Build ${versionCode})`);
  console.log(`Release Notes : ${notes}`);
  console.log(`APK Download  : ${apkUrl}`);
  console.log(`Metadata File : ${metaFileName}`);
  console.log('===========================================================');
  console.log(`📱 Your phone (${targetNumber}) will now detect this update!\n`);
}

main().catch((err) => {
  console.error('\n❌ Unexpected error:', err);
  process.exit(1);
});
